### ISSUE TITLE
Greeter tutorial asks user to run commands that no longer exist.

### ISSUE THREAD

**Issue by awochna** [ethereum/ethereum-org#759]
The first tutorial used by new developers entering the smart contract development world start by having you run the following to make sure solidity is installed:

```
eth.getCompilers()
```

When I run this in geth (v1.7.3), I get told that it doesn't exist, despite Solidity being installed:

```
Error: The method eth_getCompilers does not exist/is not available
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

Trying to just continue and compile the first example leads to a similar error:

```
Error: The method eth_compileSolidity does not exist/is not available
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:23
```

From here, I have no idea how to continue the tutorial.

It seems that geth has removed the solidity parser (https://github.com/ethereum/go-ethereum/issues/3793) but that this documentation has not yet been updated. It looks like the status of this feature is in flux, but in the meantime we're making the ecosystem less accessible to new developers by not at least adding a side note in these tutorials.

**Comment by jiaxyan** [comment]
yes, this is so unresonable! I 've  notice this bugs in geth 1.6 and I was told this feature is removed in geth 1.6, but now the 1.7 version has come and the **Contract Tutorial** (Felix Lange edited this page on 20 Dec 2017)  which updated at Dec 2017 still told us to do this... I don't know, am I missing something that make my developing contracts so difficult...

**Comment by awochna** [comment]
@jiaxyan I don't think you're missing anything. This documentation has been left behind and current introductory documentation really helps build community, so all I can think this is an indicator of priority for Ethereum/Geth/Solidity's direction.

That being said, if you want to keep developing smart contracts using some different documentation, check out Truffle (http://truffleframework.com/docs/) and of course the Solidity documentation.

**Comment by jbarros35** [comment]
Well there is another problem on this tutorial

Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Greeter contract constructor expected 1 arguments, received 0
